build:
    tests:
        override:
            -
                command: 'bin/dev build'
                coverage:
                    file: 'reports/clover-coverage.xml'
                    format: 'clover'

