language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script: echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: bin/dev build

branches:
  only:
    - develop
    - master
