services:

  preprocessor.processors.conditionalbefore.haspredefineditems:
    class:     Itq\Common\Plugin\ConditionalBeforeProcessor\HasPredefinedItemsConditionalBeforeProcessor
    tags:      [{name: 'preprocessor.conditionalbefore'}]
    public:    false
