security_login:
  path:     /login
  methods:  [GET, POST]
  defaults:
    _controller: ItqBundle:Security:login

security_logout:
  path:     /logout
  methods:  [GET]
  defaults:
    _controller: ItqBundle:Security:logout

security_reset_password:
  path:     /reset-password
  methods:  [GET, POST]
  defaults:
    _controller: ItqBundle:Security:resetPassword

security_check:
  path:     /login_check
  methods:  [POST]
  defaults:
    _controller: ItqBundle:Security:loginCheck
