services:

  # plugins/httprotocolhandler

  itq.httpprotocolhandler.native:
    class:     Itq\Common\Plugin\HttpProtocolHandler\NativeHttpProtocolHandler
    tags:      [{name: 'app.httprotocolhandler', protocols: 'http,https', methods: 'GET'}]


  # plugins/generators

  itq.generator.password:
    class:     Itq\Common\Plugin\Generator\PasswordGenerator
    arguments: ['@app.password', '@app.vault']
    tags:      [{name: 'app.generator'}]
  itq.generator.string:
    class:     Itq\Common\Plugin\Generator\StringGenerator
    arguments: ['%app_default_device_platform%', '%app_storage_url_pattern%', '%app_dynamic_url_patterns%']
    tags:      [{name: 'app.generator'}]


  # plugins/migrators

  itq.migrator.php:
    class:     Itq\Common\Plugin\Migrator\PhpMigrator
    calls:     [['setEventDispatcher', ['@event_dispatcher']]]
    tags:      [{name: 'app.migrator', extension: 'php'}]
  itq.migrator.sh:
    class:     Itq\Common\Plugin\Migrator\ShMigrator
    calls:     [['setEventDispatcher', ['@event_dispatcher']]]
    tags:      [{name: 'app.migrator', extension: 'sh'}]
  itq.migrator.yaml:
    class:     Itq\Common\Plugin\Migrator\YamlMigrator
    arguments: ['@app.yaml']
    tags:      [{name: 'app.migrator', extension: 'yaml'}]


  # plugins/actions

  itq.action.addvar:
    class:     Itq\Common\Plugin\Action\AddVarAction
    arguments: ['@service_container']
    tags:      [{name: 'app.action'}]
  itq.action.mail:
    class:     Itq\Common\Plugin\Action\MailAction
    arguments: ['@app.template', '@translator', '@app.attachment', '@app.customizer', '@event_dispatcher', '%app_senders%', '%app_recipients%', '%app_env%', '@request_stack', '@app.tenant', '%locale%']
    tags:      [{name: 'app.action'}]
  itq.action.pushnotification:
    class:     Itq\Common\Plugin\Action\PushNotificationAction
    arguments: ['@app.template', '@translator', '@app.attachment', '@app.customizer', '@event_dispatcher', '%app_senders%', '%app_recipients%', '%app_env%', '@request_stack', '@app.tenant', '%locale%']
    tags:      [{name: 'app.action'}]
  itq.action.sms:
    class:     Itq\Common\Plugin\Action\SmsAction
    arguments: ['@app.template', '@translator', '@app.attachment', '@app.customizer', '@event_dispatcher', '%app_senders%', '%app_recipients%', '%app_env%', '@request_stack', '@app.tenant', '%locale%']
    tags:      [{name: 'app.action'}]
  itq.action.task:
    class:     Itq\Common\Plugin\Action\TaskAction
    arguments: ['@app.task', '@app.crud']
    tags:      [{name: 'app.action'}]


  # plugins/codegenerators

  itq.codegenerator.sdk:
    class:     Itq\Common\Plugin\CodeGenerator\SdkCodeGenerator
    tags:      [{name: 'app.codeGenerator'}]


  # plugins/connectionbags

  itq.connectionbag.mongo:
    class:     Itq\Common\Plugin\ConnectionBag\MongoConnectionBag
    arguments: [[]]
    tags:      [{name: 'app.connection_bag', type: 'mongo'}]


  # plugins/datacollectors

  itq.datacollector.database:
    class: Itq\Common\Plugin\DataCollector\DatabaseDataCollector
    arguments: ['%kernel.debug%']
    tags:
      - { name: 'data_collector', template: 'ItqBundle:data-collector:database.html.twig', id: 'app_database'}
      - { name: 'kernel.event_listener', event: 'database.query.executed', method: 'onDatabaseQueryExecuted'}


  # plugins/documentbuilders

  itq.documentbuilder.excel:
    class:     Itq\Common\Plugin\DocumentBuilder\ExcelDocumentBuilder
    tags:      [{name: 'app.document_builder', type: 'excel'}]


  # plugins/exceptiondescriptors

  itq.exceptiondescriptor.authenticationexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\AuthenticationExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.bulkexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\BulkExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.errorexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\ErrorExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.formvalidationexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\FormValidationExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.methodnotallowedhttpexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\MethodNotAllowedHttpExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.namedbusinessruleexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\NamedBusinessRuleExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.notfoundhttpexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\NotFoundHttpExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.unsupportedaccounttypeexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\UnsupportedAccountTypeExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]


  # plugins/formatters

  itq.formatter.excel:
    class:     Itq\Common\Plugin\Formatter\ExcelFormatter
    arguments: ['@app.documentbuilder']
    tags:      [{name: 'app.formatter'}]
  itq.formatter.json:
    class:     Itq\Common\Plugin\Formatter\JsonFormatter
    arguments: ['@jms_serializer']
    tags:      [{name: 'app.formatter'}]
  itq.formatter.xml:
    class:     Itq\Common\Plugin\Formatter\XmlFormatter
    arguments: ['@jms_serializer']
    tags:      [{name: 'app.formatter'}]
  itq.formatter.yaml:
    class:     Itq\Common\Plugin\Formatter\YamlFormatter
    arguments: ['@app.yaml']
    tags:      [{name: 'app.formatter'}]


  # plugins/ruletypes

  itq.ruletype.value:
    class:     Itq\Common\Plugin\RuleType\ValueRuleType
    arguments: ['@app.expression']
    tags:      [{name: 'app.rule_type'}]


  # plugins/typeguessbuilders

  itq.typeguessbuilder.basiclist:
    class: Itq\Common\Plugin\TypeGuessBuilder\BasicListTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: basicList}]
  itq.typeguessbuilder.boolean:
    class: Itq\Common\Plugin\TypeGuessBuilder\BooleanTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: boolean}]
  itq.typeguessbuilder.embeddedlist:
    class: Itq\Common\Plugin\TypeGuessBuilder\EmbeddedListTypeGuessBuilder
    arguments:
      - '@app.metadata'
    tags: [{name: app.typeguessbuilder, id: embeddedList}]
  itq.typeguessbuilder.embeddedreference:
    class: Itq\Common\Plugin\TypeGuessBuilder\EmbeddedReferenceTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: embeddedReference}]
  itq.typeguessbuilder.embedded:
    class: Itq\Common\Plugin\TypeGuessBuilder\EmbeddedTypeGuessBuilder
    arguments:
      - '@app.metadata'
    tags: [{name: app.typeguessbuilder, id: embedded}]
  itq.typeguessbuilder.enum:
    class: Itq\Common\Plugin\TypeGuessBuilder\EnumTypeGuessBuilder
    arguments:
      - '@app.metadata'
    tags: [{name: app.typeguessbuilder, id: enum}]
  itq.typeguessbuilder.hashList:
    class: Itq\Common\Plugin\TypeGuessBuilder\HashListTypeGuessBuilder
    arguments:
      - '@app.metadata'
    tags: [{name: app.typeguessbuilder, id: hashList}]
  itq.typeguessbuilder.id:
    class: Itq\Common\Plugin\TypeGuessBuilder\IdTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: id}]
  itq.typeguessbuilder.reference:
    class: Itq\Common\Plugin\TypeGuessBuilder\ReferenceTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: reference}]
  itq.typeguessbuilder.storage:
    class: Itq\Common\Plugin\TypeGuessBuilder\StorageTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: storage}]
  itq.typeguessbuilder.taglist:
    class: Itq\Common\Plugin\TypeGuessBuilder\TagListTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: tagList}]
  itq.typeguessbuilder.unknown:
    class: Itq\Common\Plugin\TypeGuessBuilder\UnknownTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: unknown}]
  itq.typeguessbuilder.witness:
    class: Itq\Common\Plugin\TypeGuessBuilder\WitnessTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: witness}]
  itq.typeguessbuilder.workflow:
    class: Itq\Common\Plugin\TypeGuessBuilder\WorkflowTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: workflow}]


  # plugins/datafilters

  itq.datafilter.modelrestrict:
    class:     Itq\Common\Plugin\DataFilter\ModelRestrictDataFilter
    arguments: ['@app.metadata']
    tags:      [{name: 'app.datafilter'}]


  # plugins/uniquecodegeneratoralgorithms

  itq.uniquecodegeneratoralgorithm.itq:
    class:     Itq\Common\Plugin\UniqueCodeGeneratorAlgorithm\ItqUniqueCodeGeneratorAlgorithm
    tags:      [{name: 'app.unique_code_generator_algorithm'}]


  # plugins/modelcleaners

  itq.modelcleaner.populatestorages:
    class:     Itq\Common\Plugin\ModelCleaner\PopulateStoragesModelCleaner
    arguments: ['@app.metadata', '@app.storage']
    tags:      [{name: 'app.modelcleaner', priority: 300}]
  itq.modelcleaner.refreshcached:
    class:     Itq\Common\Plugin\ModelCleaner\RefreshCachedModelCleaner
    arguments: ['@app.metadata', '@app.crud']
    tags:      [{name: 'app.modelcleaner', priority: 280}]
  itq.modelcleaner.refreshembeddedreferencelinks:
    class:     Itq\Common\Plugin\ModelCleaner\RefreshEmbeddedReferenceLinksModelCleaner
    arguments: ['@app.metadata', '@app.crud']
    tags:      [{name: 'app.modelcleaner', priority: 290}]
  itq.modelcleaner.triggertrackers:
    class:     Itq\Common\Plugin\ModelCleaner\TriggerTrackersModelCleaner
    arguments: ['@app.metadata', '@app.crud', '@app.expression']
    tags:      [{name: 'app.modelcleaner', priority: 270}]


  # plugins/modeldynamicpropertybuilders

  itq.modeldynamicpropertybuilder.dynamicurls:
    class:     Itq\Common\Plugin\ModelDynamicPropertyBuilder\DynamicUrlsModelDynamicPropertyBuilder
    arguments: ['@app.dynamicurl']
    tags:      [{name: 'app.modeldynamicpropertybuilder', priority: 260}]
  itq.modeldynamicpropertybuilder.storageurls:
    class:     Itq\Common\Plugin\ModelDynamicPropertyBuilder\StorageUrlsModelDynamicPropertyBuilder
    arguments: ['@app.metadata', '@app.crud', '@app.generator']
    tags:      [{name: 'app.modeldynamicpropertybuilder', priority: 270}]
  itq.modeldynamicpropertybuilder.virtualembeddedreferencelists:
    class:     Itq\Common\Plugin\ModelDynamicPropertyBuilder\VirtualEmbeddedReferenceListsModelDynamicPropertyBuilder
    arguments: ['@app.metadata', '@app.crud']
    tags:      [{name: 'app.modeldynamicpropertybuilder', priority: 300}]
  itq.modeldynamicpropertybuilder.virtualembeddedreferences:
    class:     Itq\Common\Plugin\ModelDynamicPropertyBuilder\VirtualEmbeddedReferencesModelDynamicPropertyBuilder
    arguments: ['@app.metadata', '@app.crud']
    tags:      [{name: 'app.modeldynamicpropertybuilder', priority: 290}]
  itq.modeldynamicpropertybuilder.virtuals:
    class:     Itq\Common\Plugin\ModelDynamicPropertyBuilder\VirtualsModelDynamicPropertyBuilder
    arguments: ['@app.metadata', '@app.crud']
    tags:      [{name: 'app.modeldynamicpropertybuilder', priority: 280}]


  # plugins/modelpropertymutators

  itq.modelpropertymutator.basiclists:
    class:     Itq\Common\Plugin\ModelPropertyMutator\BasicListsModelPropertyMutator
    tags:      [{name: 'app.modelpropertymutator', priority: 280}]
  itq.modelpropertymutator.cachedlists:
    class:     Itq\Common\Plugin\ModelPropertyMutator\CachedListsModelPropertyMutator
    tags:      [{name: 'app.modelpropertymutator', priority: 240}]
  itq.modelpropertymutator.embeddedlists:
    class:     Itq\Common\Plugin\ModelPropertyMutator\EmbeddedListsModelPropertyMutator
    tags:      [{name: 'app.modelpropertymutator', priority: 250}]
  itq.modelpropertymutator.embeddedreferences:
    class:     Itq\Common\Plugin\ModelPropertyMutator\EmbeddedReferencesModelPropertyMutator
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelpropertymutator', priority: 300}]
  itq.modelpropertymutator.embeddeds:
    class:     Itq\Common\Plugin\ModelPropertyMutator\EmbeddedsModelPropertyMutator
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelpropertymutator', priority: 290}]
  itq.modelpropertymutator.hashlists:
    class:     Itq\Common\Plugin\ModelPropertyMutator\HashListsModelPropertyMutator
    tags:      [{name: 'app.modelpropertymutator', priority: 260}]
  itq.modelpropertymutator.taglists:
    class:     Itq\Common\Plugin\ModelPropertyMutator\TagListsModelPropertyMutator
    tags:      [{name: 'app.modelpropertymutator', priority: 270}]
  itq.modelpropertymutator.types:
    class:     Itq\Common\Plugin\ModelPropertyMutator\TypesModelPropertyMutator
    tags:      [{name: 'app.modelpropertymutator', priority: 230}]


  # plugins/modelrefreshers

  itq.modelrefresher.buildgenerateds:
    class:     Itq\Common\Plugin\ModelRefresher\BuildGeneratedsModelRefresher
    arguments: ['@app.metadata', '@app.generator']
    tags:      [{name: 'app.modelrefresher', priority: 200}]
  itq.modelrefresher.checkbasiclists:
    class:     Itq\Common\Plugin\ModelRefresher\CheckBasicListsModelRefresher
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelrefresher', priority: 240}]
  itq.modelrefresher.checkembeddedlists:
    class:     Itq\Common\Plugin\ModelRefresher\CheckEmbeddedListsModelRefresher
    arguments: ['@app.metadata', '@app.crud']
    tags:      [{name: 'app.modelrefresher', priority: 260}]
  itq.modelrefresher.checkembeddeds:
    class:     Itq\Common\Plugin\ModelRefresher\CheckEmbeddedsModelRefresher
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelrefresher', priority: 250}]
  itq.modelrefresher.checkhashlist:
    class:     Itq\Common\Plugin\ModelRefresher\CheckHashListsModelRefresher
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelrefresher', priority: 220}]
  itq.modelrefresher.checkreferences:
    class:     Itq\Common\Plugin\ModelRefresher\CheckReferencesModelRefresher
    arguments: ['@app.metadata', '@app.crud']
    tags:      [{name: 'app.modelrefresher', priority: 280}]
  itq.modelrefresher.checktaglists:
    class:     Itq\Common\Plugin\ModelRefresher\CheckTagListsModelRefresher
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelrefresher', priority: 230}]
  itq.modelrefresher.computefingerprints:
    class:     Itq\Common\Plugin\ModelRefresher\ComputeFingerPrintsModelRefresher
    arguments: ['@app.metadata', '@app.generator']
    tags:      [{name: 'app.modelrefresher', priority: 190}]
  itq.modelrefresher.convertscalarproperties:
    class:     Itq\Common\Plugin\ModelRefresher\ConvertScalarPropertiesModelRefresher
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelrefresher', priority: 290}]
  itq.modelrefresher.defaultvaluesloader:
    class:     Itq\Common\Plugin\ModelRefresher\DefaultValuesLoaderModelRefresher
    arguments: ['@app.metadata', '@app.tenant', '@app.generator']
    tags:      [{name: 'app.modelrefresher', priority: 300}]
  itq.modelrefresher.fetchembeddedreferences:
    class:     Itq\Common\Plugin\ModelRefresher\FetchEmbeddedReferencesModelRefresher
    arguments: ['@app.metadata', '@app.crud']
    tags:      [{name: 'app.modelrefresher', priority: 270}]
  itq.modelrefresher.savestorages:
    class:     Itq\Common\Plugin\ModelRefresher\SaveStoragesModelRefresher
    arguments: ['@app.metadata', '@app.storage']
    tags:      [{name: 'app.modelrefresher', priority: 180}]
  itq.modelrefresher.triggerrefreshes:
    class:     Itq\Common\Plugin\ModelRefresher\TriggerRefreshesModelRefresher
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelrefresher', priority: 210}]
  itq.modelrefresher.updatewitnesses:
    class:     Itq\Common\Plugin\ModelRefresher\UpdateWitnessesModelRefresher
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelrefresher', priority: 170}]


  # plugins/modelrestricters

  app.modelrestricter.registered:
    class:     Itq\Common\Plugin\ModelRestricter\RegisteredModelRestricter
    arguments: ['@app.metadata', '@app.crud', '@app.expression']
    tags:      [{name: 'app.modelrestricter', priority: 300}]


  # plugins/modelupdateenrichers

  app.modelupdateenricher.toggleitems:
    class:     Itq\Common\Plugin\ModelUpdateEnricher\ToggleItemsModelUpdateEnricher
    tags:      [{name: 'app.modelupdateenricher', priority: 300}]


  # plugins/modelfieldlistfilters

  app.modelfieldlistfilter.requirements:
    class:     Itq\Common\Plugin\ModelFieldListFilter\RequirementsFieldListFilter
    arguments: ['@app.metadata']
    tags:      [{name: 'app.modelfieldlistfilter', priority: 300}]


  # plugins/modelpropertylinearizers

  app.modelpropertylinearizer.datetime:
    class:     Itq\Common\Plugin\ModelPropertyLinearizer\DateTimeModelPropertyLinearizer
    tags:      [{name: 'app.modelpropertylinearizer', priority: 300}]
  app.modelpropertylinearizer.geopoint:
    class:     Itq\Common\Plugin\ModelPropertyLinearizer\GeoPointModelPropertyLinearizer
    tags:      [{name: 'app.modelpropertylinearizer', priority: 290}]
  app.modelpropertylinearizer.hash:
    class:     Itq\Common\Plugin\ModelPropertyLinearizer\HashModelPropertyLinearizer
    tags:      [{name: 'app.modelpropertylinearizer', priority: 280}]


  # plugins/modelpropertyauthorizationcheckers

  app.modelpropertyauthorizationcheckers.secure:
    class:     Itq\Common\Plugin\ModelPropertyAuthorizationChecker\SecureModelPropertyAuthorizationChecker
    arguments: ['@app.metadata', '@security.authorization_checker']
    tags:      [{name: 'app.modelpropertyauthorizationchecker', priority: 300}]
