services:
  preprocessor.annotationreader:
    class: Doctrine\Common\Annotations\AnnotationReader
  preprocessor.preprocessable_class_finder:
    class: Itq\Common\PreprocessableClassFinder
    arguments:
      - '@preprocessor.annotationreader'
  preprocessor.preprocessor:
    class: Itq\Common\Service\PreprocessorService
    arguments:
      - '@preprocessor.annotationreader'
      - '@preprocessor.preprocessable_class_finder'

  preprocessor.contextdumpers.phpfile:
    class:     Itq\Common\Plugin\ContextDumper\PhpFileContextDumper
    tags:      [{name: preprocessor.contextdumper}]
  preprocessor.contextdumpers.yamlfile:
    class:     Itq\Common\Plugin\ContextDumper\YamlFileContextDumper
    arguments: ['@app.yaml']
    tags:      [{name: preprocessor.contextdumper}]

  preprocessor.processors.storage.file:
    class: Itq\Common\Plugin\StorageProcessor\FileStorageProcessor
    tags: [{name: preprocessor.storage}]
  preprocessor.processors.storage.memory:
    class: Itq\Common\Plugin\StorageProcessor\MemoryStorageProcessor
    tags: [{name: preprocessor.storage}]
  preprocessor.processors.storage.database:
    class: Itq\Common\Plugin\StorageProcessor\DatabaseStorageProcessor
    tags: [{name: preprocessor.storage}]
  preprocessor.processors.storage.googledrive:
    class: Itq\Common\Plugin\StorageProcessor\GoogleDriveStorageProcessor
    tags: [{name: preprocessor.storage}]
  preprocessor.processors.storage.redis:
    class: Itq\Common\Plugin\StorageProcessor\RedisStorageProcessor
    tags: [{name: preprocessor.storage}]

  preprocessor.processors.annotation.preclass.model:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassAnnotation\ModelClassAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: preClass}]
  preprocessor.processors.annotation.class.stat:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassAnnotation\StatClassAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: class}]
  preprocessor.processors.annotation.class.restrict:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassAnnotation\RestrictClassAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: class}]
  preprocessor.processors.annotation.classmethod.sdk:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassMethodAnnotation\SdkClassMethodAnnotationProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.annotation, type: classMethod}]
  preprocessor.processors.annotation.classproperty.reference:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\ReferenceClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.embeddedreference:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\EmbeddedReferenceClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.embedded:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\EmbeddedClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.hashlist:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\HashListClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.basiclist:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\BasicListClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.taglist:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\TagListClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.virtualembeddedreferencelist:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\VirtualEmbeddedReferenceListClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.virtualembeddedreference:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\VirtualEmbeddedReferenceClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.embeddedlist:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\EmbeddedListClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.cachedlist:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\CachedListClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.refresh:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\RefreshClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.exposerestrict:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\ExposeRestrictClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.secure:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\SecureClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.enum:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\EnumClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.defaultvalue:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\DefaultValueClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.generated:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\GeneratedClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.fingerprint:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\FingerPrintClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.geopoint:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\GeoPointClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.witness:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\WitnessClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.requirement:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\RequirementClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.storageurl:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\StorageUrlClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.dynamicurl:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\DynamicUrlClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.storage:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\StorageClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.workflow:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\WorkflowClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.id:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\IdClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.virtual:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\VirtualClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]
  preprocessor.processors.annotation.classproperty.jmstype:
    class: Itq\Common\Plugin\AnnotationProcessor\ClassPropertyAnnotation\JmsTypeClassPropertyAnnotationProcessor
    tags: [{name: preprocessor.annotation, type: classProperty}]

  preprocessor.processors.tag.repository:
    class: Itq\Common\Plugin\TagProcessor\RepositoryTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.crud:
    class: Itq\Common\Plugin\TagProcessor\CrudTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.subcrud:
    class: Itq\Common\Plugin\TagProcessor\SubCrudTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.volatile:
    class: Itq\Common\Plugin\TagProcessor\VolatileTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.subvolatile:
    class: Itq\Common\Plugin\TagProcessor\SubVolatileTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.providerclient:
    class: Itq\Common\Plugin\TagProcessor\ProviderClientTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.provideraccount:
    class: Itq\Common\Plugin\TagProcessor\ProviderAccountTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.providertoken:
    class: Itq\Common\Plugin\TagProcessor\ProviderTokenTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.migrator:
    class: Itq\Common\Plugin\TagProcessor\MigratorTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.datafilter:
    class: Itq\Common\Plugin\TagProcessor\DataFilterTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.workflowexecutor:
    class: Itq\Common\Plugin\TagProcessor\WorkflowExecutorTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.expressionlanguageprovider:
    class: Itq\Common\Plugin\TagProcessor\ExpressionLanguageProviderTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.sdkgenerator:
    class: Itq\Common\Plugin\TagProcessor\SdkGeneratorTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.httpprotocolhandler:
    class: Itq\Common\Plugin\TagProcessor\HttpProtocolHandlerTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.action:
    class: Itq\Common\Plugin\TagProcessor\ActionTagProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.typeguessbuilder:
    class: Itq\Common\Plugin\TagProcessor\TypeGuessBuilderTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.businessrule:
    class: Itq\Common\Plugin\TagProcessor\BusinessRuleTagProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.generator:
    class: Itq\Common\Plugin\TagProcessor\GeneratorTagProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.grouptype:
    class: Itq\Common\Plugin\TagProcessor\GroupTypeTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.partner:
    class: Itq\Common\Plugin\TagProcessor\PartnerTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.ruletype:
    class: Itq\Common\Plugin\TagProcessor\RuleTypeTagProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.codegenerator:
    class: Itq\Common\Plugin\TagProcessor\CodeGeneratorTagProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.formatter:
    class: Itq\Common\Plugin\TagProcessor\FormatterTagProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.uniquecodegeneratoralgorithm:
    class: Itq\Common\Plugin\TagProcessor\UniqueCodeGeneratorAlgorithmTagProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.customizer:
    class: Itq\Common\Plugin\TagProcessor\CustomizerTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.paymentprovider:
    class: Itq\Common\Plugin\TagProcessor\PaymentProviderTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.task:
    class: Itq\Common\Plugin\TagProcessor\TaskTagProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.jobtype:
    class: Itq\Common\Plugin\TagProcessor\JobTypeTagProcessor
    arguments:
      - '@preprocessor.annotationreader'
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.storage:
    class: Itq\Common\Plugin\TagProcessor\StorageTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.connectionbag:
    class: Itq\Common\Plugin\TagProcessor\ConnectionBagTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.documentbuilder:
    class: Itq\Common\Plugin\TagProcessor\DocumentBuilderTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.repositoriesaware:
    class: Itq\Common\Plugin\TagProcessor\RepositoriesAwareTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.crudsaware:
    class: Itq\Common\Plugin\TagProcessor\CrudsAwareTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.exceptiondescriptor:
    class: Itq\Common\Plugin\TagProcessor\ExceptionDescriptorTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.modelcleaner:
    class: Itq\Common\Plugin\TagProcessor\ModelCleanerTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.modeldynamicpropertybuilder:
    class: Itq\Common\Plugin\TagProcessor\ModelDynamicPropertyBuilderTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.modelfieldlistfilter:
    class: Itq\Common\Plugin\TagProcessor\ModelFieldListFilterTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.modelpropertyauthorizationchecker:
    class: Itq\Common\Plugin\TagProcessor\ModelPropertyAuthorizationCheckerTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.modelpropertylinearizer:
    class: Itq\Common\Plugin\TagProcessor\ModelPropertyLinearizerTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.modelpropertymutator:
    class: Itq\Common\Plugin\TagProcessor\ModelPropertyMutatorTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.modelrefresher:
    class: Itq\Common\Plugin\TagProcessor\ModelRefresherTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.modelrestricter:
    class: Itq\Common\Plugin\TagProcessor\ModelRestricterTagProcessor
    tags: [{name: preprocessor.tag}]
  preprocessor.processors.tag.modelupdateenricher:
    class: Itq\Common\Plugin\TagProcessor\ModelUpdateEnricherTagProcessor
    tags: [{name: preprocessor.tag}]

  preprocessor.processors.conditionalbefore.haspredefineditems:
    class: Itq\Common\Plugin\ConditionalBeforeProcessor\HasPredefinedItemsConditionalBeforeProcessor
    tags: [{name: preprocessor.conditionalbefore}]

