parameters:

  app_env: local
  app_security_client_secret: myclientsecret
  app_security_user_secret: myusersecret
  app_security_instance_secret: myinstancesecret
  app_security_instance_creation_secret: myinstancecreationsecret
  app_googledrive_application: unknown
  app_instance_allowed_id_patterns: ['/^test_[a-z0-9]{5,59}$/']

services:

  app.filesystem.adapter.native:
    class:     Itq\Common\Adapter\Filesystem\NativeFilesystemAdapter
  app.php.adapter.native:
    class:     Itq\Common\Adapter\Php\NativePhpAdapter
  app.system.adapter.native:
    class:     Itq\Common\Adapter\System\NativeSystemAdapter
  app.symfony.adapter.native:
    class:     Itq\Common\Adapter\Symfony\NativeSymfonyAdapter

  app.action:
    class:     Itq\Common\Service\ActionService
    lazy:      true
    arguments: ['@app.expression']
  app.address:
    class:     Itq\Common\Service\AddressService
    arguments: ['@app.http', '%app_api_adresse_url%']
  app.archiver:
    class:     Itq\Common\Service\ArchiverService
  app.attachment:
    class:     Itq\Common\Service\AttachmentService
    arguments: ['@app.generator', '@app.filesystem']
  app.batch:
    class:     Itq\Common\Service\BatchService
    arguments: ['@event_dispatcher']
  app.businessrule:
    class:     Itq\Common\Service\BusinessRuleService
    lazy:      true
    arguments: ['@app.tenant', '@app.context']
    tags:      [{name: 'app.workflowexecutor'}]
  app.callable:
    class:     Itq\Common\Service\CallableService
  app.codegenerator:
    class:     Itq\Common\Service\CodeGeneratorService
  app.collection:
    class:     Itq\Common\Service\CollectionService
    arguments: ['@app.criterium']
  app.connection:
    class:     Itq\Common\Service\ConnectionService
  app.context:
    class:     Itq\Common\Service\ContextService
    arguments: [{'env': '%app_env%'}]
  app.converter:
    class:     Itq\Common\Service\ConverterService
  app.criterium:
    class:     Itq\Common\Service\CriteriumService
    tags:      [{name: 'itq.aware.criteriumtype'}]
  app.crud:
    class:     Itq\Common\Service\CrudService
    lazy:      true
    tags:      [{name: 'app.cruds_aware', method: 'add'}]
  app.customizer:
    class:     Itq\Common\Service\CustomizerService
  app.data:
    class:     Itq\Common\Service\DataService
  app.database.mongo:
    class:     Itq\Common\Service\Database\MongoDatabaseService
    arguments: ['@app.criterium', '@app.connection', '@event_dispatcher', '@app.storage', '@app.generator']
    calls:     [['setErrorManager', ['@app.errormanager']]]
  app.datafilter:
    class:     Itq\Common\Service\DataFilterService
    arguments: ['@request_stack', '@security.token_storage']
  app.dataprovider:
    class:     Itq\Common\Service\DataProviderService
    tags:      [{name: 'itq.aware.dataprovider'}]
  app.provider:
    class:     Itq\Common\Service\DataFilterService
    arguments: ['@request_stack', '@security.token_storage']
  app.date:
    class:     Itq\Common\Service\DateService
    arguments: ['@app.system']
  app.doc:
    class:     Itq\Common\Service\DocService
  app.documentbuilder:
    class:     Itq\Common\Service\DocumentBuilderService
  app.dynamicurl:
    class:     Itq\Common\Service\DynamicUrlService
    arguments: ['@app.generator']
  app.errormanager:
    class:     Itq\Common\ErrorManager
    arguments: ['@translator', '%locale%']
  app.event:
    class:     Itq\Common\Service\EventService
    lazy:      true
    arguments: ['@app.action', '@app.context']
  app.exception:
    class:     Itq\Common\Service\ExceptionService
    arguments: ['@request_stack']
  app.expression:
    class:     Itq\Common\Service\ExpressionService
    arguments: ['@app.template', '@app.expression_language']
  app.filesystem:
    class:     Itq\Common\Service\FilesystemService
    arguments: ['@app.system', '@app.filesystem.adapter.native']
  app.form:
    class:     Itq\Common\Service\FormService
    arguments: ['@form.factory']
  app.formatter:
    class:     Itq\Common\Service\FormatterService
  app.generator:
    class:     Itq\Common\Service\GeneratorService
    lazy:      true
  app.google:
    class:     Itq\Common\Service\GoogleService
    arguments: ['%app_googledrive_application%', '%app_googledrive_client%', '%app_googledrive_project%', '%app_googledrive_secret%', '%app_googledrive_storage_dir%/%app_googledrive_storage_access_token_name%']
  app.http:
    class:     Itq\Common\Service\HttpService
  app.jobtype:
    class:     Itq\Common\Service\JobTypeService
  app.json:
    class:     Itq\Common\Service\JsonService
  app.math:
    class:     Itq\Common\Service\MathService
  app.metadata:
    class:     Itq\Common\Service\MetaDataService
    lazy:      true
    arguments: ['%kernel.cache_dir%/preprocessor.php']
  app.migration:
    class:     Itq\Common\Service\MigrationService
    arguments: ['@app.database.mongo', '@logger', '@app.form', '@service_container', 'migration', '%app_db_dir%', '%app_env%']
  app.modelstats:
    class:     Itq\Common\Service\ModelStatsService
    arguments: ['@app.metadata', '@app.crud', '@app.expression']
  app.model:
    class:     Itq\Common\Service\ModelService
    lazy:      true
    arguments:
      - '@app.model.cleaner'
      - '@app.model.restricter'
      - '@app.model.updateenricher'
      - '@app.model.objectpopulator'
      - '@app.model.refresher'
      - '@app.model.fieldlistfilter'
      - '@app.model.dynamicurlbuilder'
      - '@app.model.propertylinearizer'
  app.model.cleaner:
    class:     Itq\Common\Service\Model\ModelCleanerService
    tags:      [{name: 'itq.aware.modelcleaner'}]
  app.model.dynamicpropertybuilder:
    class:     Itq\Common\Service\Model\ModelDynamicPropertyBuilderService
    arguments: ['@app.metadata']
    tags:      [{name: 'itq.aware.modeldynamicpropertybuilder'}]
  app.model.dynamicurlbuilder:
    class:     Itq\Common\Service\Model\ModelDynamicUrlBuilderService
    arguments: ['@app.metadata', '@app.dynamicurl']
  app.model.fieldlistfilter:
    class:     Itq\Common\Service\Model\ModelFieldListFilterService
    tags:      [{name: 'itq.aware.modelfieldlistfilter'}]
  app.model.objectpopulator:
    class:     Itq\Common\Service\Model\ModelObjectPopulatorService
    arguments: ['@app.metadata', '@app.storage', '@app.model.propertymutator', '@app.model.dynamicpropertybuilder']
  app.model.propertyauthorizationchecker:
    class:     Itq\Common\Service\Model\ModelPropertyAuthorizationCheckerService
    tags:      [{name: 'itq.aware.modelpropertyauthorizationchecker'}]
  app.model.propertylinearizer:
    class:     Itq\Common\Service\Model\ModelPropertyLinearizerService
    arguments: ['@app.metadata']
    tags:      [{name: 'itq.aware.modelpropertylinearizer'}]
  app.model.propertymutator:
    class:     Itq\Common\Service\Model\ModelPropertyMutatorService
    arguments: ['@app.metadata', '@app.model.propertyauthorizationchecker']
    tags:      [{name: 'itq.aware.modelpropertymutator'}]
  app.model.refresher:
    class:     Itq\Common\Service\Model\ModelRefresherService
    arguments: ['@app.metadata', '@app.model.restricter']
    tags:      [{name: 'itq.aware.modelrefresher'}]
  app.model.restricter:
    class:     Itq\Common\Service\Model\ModelRestricterService
    tags:      [{name: 'itq.aware.modelrestricter'}]
  app.model.updateenricher:
    class:     Itq\Common\Service\Model\ModelUpdateEnricherService
    arguments: ['@app.metadata']
    tags:      [{name: 'itq.aware.modelupdateenricher'}]
  app.partner:
    class:     Itq\Common\Service\PartnerService
  app.password:
    class:     Itq\Common\Service\PasswordService
  app.php:
    class:     Itq\Common\Service\PhpService
    arguments: ['@app.php.adapter.native']
  app.pollablesource:
    class:     Itq\Common\Service\PollableService
  app.poller:
    class:     Itq\Common\Service\PollerService
  app.queuecollection:
    class:     Itq\Common\Service\QueueCollectionService
  app.request:
    class:     Itq\Common\Service\RequestService
  app.response:
    class:     Itq\Common\Service\ResponseService
    arguments: ['@app.formatter', '@app.exception']
  app.ruleengine:
    class:     Itq\Common\Service\RuleEngineService
  app.sdk:
    class:     Itq\Common\Service\SdkService
  app.shipping:
    class:     Itq\Common\Service\ShippingService
    arguments: ['@app.date']
  app.storage:
    class:     Itq\Common\Service\StorageService
    lazy:      true
    arguments: ['@event_dispatcher']
  app.storedfile:
    class:     Itq\Common\Service\StoredFileService
    arguments: ['@app.metadata', '@app.crud']
    calls:     [[setErrorManager, ["@app.errormanager"]]]
  app.string:
    class:     Itq\Common\Service\StringService
  app.supervision:
    class:     Itq\Common\Service\SupervisionService
    arguments: ['@app.dataprovider']
  app.symfony:
    class:     Itq\Common\Service\SymfonyService
    arguments: ['@app.symfony.adapter.native']
  app.system:
    class:     Itq\Common\Service\SystemService
    arguments: ['@app.system.adapter.native']
  app.task:
    class:     Itq\Common\Service\TaskService
  app.template:
    class:     Itq\Common\Service\TemplateService
    lazy:      true
    arguments: ['@templating']
  app.tenant:
    class:     Itq\Common\Service\TenantService
    arguments: ['@security.token_storage', '%app_default_tenant%']
  app.tokenprovider:
    class:     Itq\Common\Service\TokenProviderService
  app.tracker:
    class:     Itq\Common\Service\TrackerService
  app.typeguess:
    class:     Itq\Common\Service\TypeGuessService
  app.userprovider:
    class:     Itq\Common\Service\UserProviderService
    arguments: ['@app.converter', '%app_user_class%']
  app.vault:
    class:     Itq\Common\Service\VaultService
    arguments: ['@app.storage']
  app.workflow:
    class:     Itq\Common\Service\WorkflowService
    arguments: [~] # will be replaced by the service with tag 'app.workflowexecutor'
  app.yaml:
    class:     Itq\Common\Service\YamlService
  app.instance:
    class:     Itq\Common\Service\InstanceService
    arguments: ['@event_dispatcher', '@app.migration', '%app_instance_allowed_id_patterns%']
    calls:     [['setErrorManager', ['@app.errormanager']]]
    tags:      [{name: 'app.provider.instance'}]

  # twig extensions

  itq.twig.extension.itq:
    class:     Itq\Common\Twig\ItqExtension
    arguments: ['%app_variables%', '@app.exception', '@app.template', '@security.token_storage', '@app.yaml']
    tags:      [{name: 'twig.extension'}]


  # twig loaders

  itq.twig.loader.string:
    class:     Twig_Extension_StringLoader
    tags:      [{name: 'twig.extension'}]


  # Symfony

  app.expression_language:
    class:     Symfony\Component\ExpressionLanguage\ExpressionLanguage
  app.annotation_reader:
    class:     Doctrine\Common\Annotations\AnnotationReader


  # others

  app.redis:
    class: Redis
    calls:
      - ['connect', ['127.0.0.1']]


  # aliases

  redis: '@app.redis'

