parameters:

  app_env: local
  app_security_client_secret: myclientsecret
  app_security_user_secret: myusersecret
  app_googledrive_application: unknown

services:

  app.action:
    class:     Itq\Common\Service\ActionService
    lazy:      true
    arguments: ['@app.callable', '@app.expression']
  app.address:
    class:     Itq\Common\Service\AddressService
    arguments: ['@app.http', '%app_api_adresse_url%']
  app.attachment:
    class:     Itq\Common\Service\AttachmentService
    arguments: ['@app.generator', '@app.filesystem']
  app.batch:
    class:     Itq\Common\Service\BatchService
    arguments: ['@event_dispatcher']
  app.businessrule:
    class:     Itq\Common\Service\BusinessRuleService
    lazy:      true
    arguments: ['@app.tenant', '@app.context']
    tags:      [{name: 'app.workflowexecutor'}]
  app.callable:
    class:     Itq\Common\Service\CallableService
  app.codegenerator:
    class:     Itq\Common\Service\CodeGeneratorService
    arguments: ['@app.callable']
  app.connection:
    class:     Itq\Common\Service\ConnectionService
  app.context:
    class:     Itq\Common\Service\ContextService
    arguments: [{'env': '%app_env%'}]
  app.crud:
    class:     Itq\Common\Service\CrudService
    lazy:      true
    tags:      [{name: 'app.cruds_aware', method: 'add'}]
  app.customizer:
    class:     Itq\Common\Service\CustomizerService
  app.data:
    class:     Itq\Common\Service\DataService
  app.database.mongo:
    class:     Itq\Common\Service\Database\MongoDatabaseService
    arguments: ['@app.connection', '@event_dispatcher', '@app.storage', '@app.generator']
    calls:     [['setErrorManager', ['@app.errormanager']]]
  app.datafilter:
    class:     Itq\Common\Service\DataFilterService
    arguments: ['@request_stack', '@security.token_storage']
  app.date:
    class:     Itq\Common\Service\DateService
  app.documentbuilder:
    class:     Itq\Common\Service\DocumentBuilderService
    arguments: ['@app.callable']
  app.errormanager:
    class:     Itq\Common\ErrorManager
    arguments: ['@translator', '%locale%']
  app.event:
    class:     Itq\Common\Service\EventService
    lazy:      true
    arguments: ['@app.action', '@app.context']
  app.exception:
    class:     Itq\Common\Service\ExceptionService
    arguments: ['@request_stack']
  app.expression:
    class:     Itq\Common\Service\ExpressionService
    arguments: ['@app.template', '@app.expression_language']
  app.filesystem:
    class:     Itq\Common\Service\FilesystemService
    arguments: ['@app.system', '@filesystem']
  app.filter:
    class:     Itq\Common\Service\FilterService
    arguments: ['@app.callable']
  app.form:
    class:     Itq\Common\Service\FormService
    arguments: ['@form.factory']
  app.formatter:
    class:     Itq\Common\Service\FormatterService
    arguments: ['@app.callable']
  app.generator:
    class:     Itq\Common\Service\GeneratorService
    lazy:      true
    arguments: ['@app.callable']
  app.google:
    class:     Itq\Common\Service\GoogleService
    arguments: ['%app_googledrive_application%', '%app_googledrive_client%', '%app_googledrive_project%', '%app_googledrive_secret%', '%app_googledrive_storage_dir%/%app_googledrive_storage_access_token_name%']
  app.http:
    class:     Itq\Common\Service\HttpService
    calls:     [['registerProtocolHandler', [['http', 'https'], '@app.httpprotocolhandler.native', ['GET']]]]
  app.jobtype:
    class:     Itq\Common\Service\JobTypeService
    arguments: ['@app.callable']
  app.json:
    class:     Itq\Common\Service\JsonService
  app.math:
    class:     Itq\Common\Service\MathService
  app.metadata:
    class:     Itq\Common\Service\MetaDataService
    lazy: true
    arguments:
      - '%kernel.cache_dir%/preprocessor.php'
      - '@app.crud'
  app.migration:
    class:     Itq\Common\Service\MigrationService
    arguments: ['@app.database.mongo', '@logger', '@app.form', '@service_container', 'migration', '%app_db_dir%', '%app_env%']
  app.model:
    class:     Itq\Common\Service\ModelService
    arguments: ['@security.authorization_checker', '@app.tenant', '@app.metadata', '@app.crud', '@app.storage', '@app.workflow', '@app.generator', '@app.expression']
  app.partner:
    class:     Itq\Common\Service\PartnerService
  app.password:
    class:     Itq\Common\Service\PasswordService
  app.request:
    class:     Itq\Common\Service\RequestService
    arguments: ['@app.userprovider', '@app.tokenprovider', '%app_security_client_secret%', '%app_security_user_secret%']
    calls:     [['setErrorManager', ['@app.errormanager']]]
  app.response:
    class:     Itq\Common\Service\ResponseService
    arguments: ['@app.formatter', '@app.exception']
  app.ruleengine:
    class:     Itq\Common\Service\RuleEngineService
    arguments: ['@app.callable']
  app.sdk:
    class:     Itq\Common\Service\SdkService
  app.shipping:
    class:     Itq\Common\Service\ShippingService
    arguments: ['@app.date']
  app.storage:
    class:     Itq\Common\Service\StorageService
    lazy:      true
    arguments: ['@event_dispatcher']
  app.storedfile:
    class:     Itq\Common\Service\StoredFileService
    arguments: ['@app.metadata', '@app.crud']
    calls:     [[setErrorManager, ["@app.errormanager"]]]
  app.string:
    class:     Itq\Common\Service\StringService
  app.system:
    class:     Itq\Common\Service\SystemService
  app.task:
    class:     Itq\Common\Service\TaskService
    arguments: ['@app.callable']
  app.template:
    class:     Itq\Common\Service\TemplateService
    lazy:      true
    arguments: ['@templating']
  app.tenant:
    class:     Itq\Common\Service\TenantService
    arguments: ['@security.token_storage', '%app_default_tenant%']
  app.tokenprovider:
    class:     Itq\Common\Service\TokenProviderService
  app.typeguess:
    class:     Itq\Common\Service\TypeGuessService
  app.userprovider:
    class:     Itq\Common\Service\UserProviderService
    arguments: ['%app_user_class%']
  app.vault:
    class:     Itq\Common\Service\VaultService
    arguments: ['@app.storage']
  app.workflow:
    class:     Itq\Common\Service\WorkflowService
    arguments: [~] # will be replaced by the service with tag 'app.workflowexecutor'
  app.yaml:
    class:     Itq\Common\Service\YamlService


  # plugins/httprotocolhandler

  itq.httpprotocolhandler.native:
    class:     Itq\Common\Plugin\HttpProtocolHandler\NativeHttpProtocolHandler


  # plugins/generators

  itq.generator.password:
    class:     Itq\Common\Plugin\Generator\PasswordGenerator
    arguments: ['@app.password', '@app.vault']
    tags:      [{name: 'app.generator'}]
  itq.generator.string:
    class:     Itq\Common\Plugin\Generator\StringGenerator
    arguments: ['%app_default_device_platform%', '%app_storage_url_pattern%', '%app_dynamic_url_patterns%']
    tags:      [{name: 'app.generator'}]


  # plugins/migrators

  itq.migrator.php:
    class:     Itq\Common\Plugin\Migrator\PhpMigrator
    calls:     [['setEventDispatcher', ['@event_dispatcher']]]
    tags:      [{name: 'app.migrator', extension: 'php'}]
  itq.migrator.sh:
    class:     Itq\Common\Plugin\Migrator\ShMigrator
    calls:     [['setEventDispatcher', ['@event_dispatcher']]]
    tags:      [{name: 'app.migrator', extension: 'sh'}]
  itq.migrator.yaml:
    class:     Itq\Common\Plugin\Migrator\YamlMigrator
    tags:      [{name: 'app.migrator', extension: 'yaml'}]


  # plugins/actions

  itq.action.addvar:
    class:     Itq\Common\Plugin\Action\AddVarAction
    arguments: ['@service_container']
    tags:      [{name: 'app.action'}]
  itq.action.mail:
    class:     Itq\Common\Plugin\Action\MailAction
    arguments: ['@app.template', '@translator', '@app.attachment', '@app.customizer', '@event_dispatcher', '%app_senders%', '%app_recipients%', '%app_env%', '@request_stack', '@app.tenant', '%locale%']
    tags:      [{name: 'app.action'}]
  itq.action.pushnotification:
    class:     Itq\Common\Plugin\Action\PushNotificationAction
    arguments: ['@app.template', '@translator', '@app.attachment', '@app.customizer', '@event_dispatcher', '%app_senders%', '%app_recipients%', '%app_env%', '@request_stack', '@app.tenant''%locale%']
    tags:      [{name: 'app.action'}]
  itq.action.sms:
    class:     Itq\Common\Plugin\Action\SmsAction
    arguments: ['@app.template', '@translator', '@app.attachment', '@app.customizer', '@event_dispatcher', '%app_senders%', '%app_recipients%', '%app_env%', '@request_stack', '@app.tenant', '%locale%']
    tags:      [{name: 'app.action'}]
  itq.action.task:
    class:     Itq\Common\Plugin\Action\TaskAction
    arguments: ['@app.task', '@app.crud']
    tags:      [{name: 'app.action'}]


  # plugins/codegenerators

  itq.codegenerator.sdk:
    class:     Itq\Common\Plugin\CodeGenerator\SdkCodeGenerator
    tags:      [{name: 'app.codeGenerator'}]


  # plugins/connectionbags

  itq.connectionbag.mongo:
    class:     Itq\Common\Plugin\ConnectionBag\MongoConnectionBag
    arguments: [[]]
    tags:      [{name: 'app.connection_bag', type: 'mongo'}]


  # plugins/datacollectors

  itq.datacollector.database:
    class: Itq\Common\Plugin\DataCollector\DatabaseDataCollector
    arguments: ['%kernel.debug%']
    tags:
      - { name: 'data_collector', template: 'ItqBundle:data-collector:database.html.twig', id: 'app_database'}
      - { name: 'kernel.event_listener', event: 'database.query.executed', method: 'onDatabaseQueryExecuted'}


  # plugins/documentbuilders

  itq.documentbuilder.excel:
    class:     Itq\Common\Plugin\DocumentBuilder\ExcelDocumentBuilder
    tags:      [{name: 'app.document_builder', type: 'excel'}]


  # plugins/exceptiondescriptors

  itq.exceptiondescriptor.authenticationexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\AuthenticationExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.bulkexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\BulkExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.errorexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\ErrorExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.formvalidationexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\FormValidationExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.methodnotallowedhttpexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\MethodNotAllowedHttpExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.namedbusinessruleexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\NamedBusinessRuleExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.notfoundhttpexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\NotFoundHttpExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]
  itq.exceptiondescriptor.unsupportedaccounttypeexception:
    class:     Itq\Common\Plugin\ExceptionDescriptor\UnsupportedAccountTypeExceptionExceptionDescriptor
    tags:      [{name: 'app.exceptiondescriptor'}]


  # plugins/formatters

  itq.formatter.excel:
    class:     Itq\Common\Plugin\Formatter\ExcelFormatter
    arguments: ['@app.documentbuilder']
    tags:      [{name: 'app.formatter'}]
  itq.formatter.json:
    class:     Itq\Common\Plugin\Formatter\JsonFormatter
    arguments: ['@jms_serializer']
    tags:      [{name: 'app.formatter'}]
  itq.formatter.xml:
    class:     Itq\Common\Plugin\Formatter\XmlFormatter
    arguments: ['@jms_serializer']
    tags:      [{name: 'app.formatter'}]
  itq.formatter.yaml:
    class:     Itq\Common\Plugin\Formatter\YamlFormatter
    tags:      [{name: 'app.formatter'}]


  # plugins/ruletypes

  itq.ruletype.sale:
    class:     Itq\Common\Plugin\RuleType\SaleRuleType
    tags:      [{name: 'app.rule_type'}]


  # plugins/typeguessbuilders

  itq.typeguessbuilder.basiclist:
    class: Itq\Common\Plugin\TypeGuessBuilder\BasicListTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: basicList}]
  itq.typeguessbuilder.boolean:
    class: Itq\Common\Plugin\TypeGuessBuilder\BooleanTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: boolean}]
  itq.typeguessbuilder.embeddedlist:
    class: Itq\Common\Plugin\TypeGuessBuilder\EmbeddedListTypeGuessBuilder
    arguments:
      - '@app.metadata'
    tags: [{name: app.typeguessbuilder, id: embeddedList}]
  itq.typeguessbuilder.embeddedreference:
    class: Itq\Common\Plugin\TypeGuessBuilder\EmbeddedReferenceTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: embeddedReference}]
  itq.typeguessbuilder.embedded:
    class: Itq\Common\Plugin\TypeGuessBuilder\EmbeddedTypeGuessBuilder
    arguments:
      - '@app.metadata'
    tags: [{name: app.typeguessbuilder, id: embedded}]
  itq.typeguessbuilder.enum:
    class: Itq\Common\Plugin\TypeGuessBuilder\EnumTypeGuessBuilder
    arguments:
      - '@app.metadata'
    tags: [{name: app.typeguessbuilder, id: enum}]
  itq.typeguessbuilder.hashList:
    class: Itq\Common\Plugin\TypeGuessBuilder\HashListTypeGuessBuilder
    arguments:
      - '@app.metadata'
    tags: [{name: app.typeguessbuilder, id: hashList}]
  itq.typeguessbuilder.id:
    class: Itq\Common\Plugin\TypeGuessBuilder\IdTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: id}]
  itq.typeguessbuilder.reference:
    class: Itq\Common\Plugin\TypeGuessBuilder\ReferenceTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: reference}]
  itq.typeguessbuilder.storage:
    class: Itq\Common\Plugin\TypeGuessBuilder\StorageTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: storage}]
  itq.typeguessbuilder.taglist:
    class: Itq\Common\Plugin\TypeGuessBuilder\TagListTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: tagList}]
  itq.typeguessbuilder.unknown:
    class: Itq\Common\Plugin\TypeGuessBuilder\UnknownTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: unknown}]
  itq.typeguessbuilder.witness:
    class: Itq\Common\Plugin\TypeGuessBuilder\WitnessTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: witness}]
  itq.typeguessbuilder.workflow:
    class: Itq\Common\Plugin\TypeGuessBuilder\WorkflowTypeGuessBuilder
    tags: [{name: app.typeguessbuilder, id: workflow}]


  # validators

  itq.validator.businessrules:
    class:     Itq\Common\Validator\Constraints\ValidationBusinessRulesValidator
    arguments: ['@app.businessrule', '@app.metadata', '@app.errormanager']
    tags:      [{name: 'validator.constraint_validator', alias: 'app_validation_business_rules'}]


  # form typeguessers

  itq.typeguesser.model:
    class:     Itq\Common\Form\TypeGuesser\ModelTypeGuesser
    arguments: ['@app.metadata', '@app.typeguess']
    tags:      [{name: 'form.type_guesser'}]


  # form types

  itq.form.type.flag:
    class:     Itq\Common\Form\Type\FlagType
    tags:      [{name: 'form.type', alias: 'app_flag'}]
  itq.form.type.integer:
    class:     Itq\Common\Form\Type\IntegerType
    tags:      [{name: 'form.type', alias: 'app_integer'}]
  itq.form.type.boolean:
    class:     Itq\Common\Form\Type\BooleanType
    tags:      [{name: 'form.type', alias: 'app_boolean'}]
  itq.form.type.mixedcollection:
    class:     Itq\Common\Form\Type\MixedCollectionType
    tags:      [{name: 'form.type', alias: 'app_mixedcollection'}]


  # twig extensions

  itq.twig.extension.itq:
    class:     Itq\Common\Twig\ItqExtension
    arguments: ['%app_variables%', '@app.exception', '@app.template', '@security.token_storage']
    tags:      [{name: 'twig.extension'}]


  # twig loaders

  itq.twig.loader.string:
    class:     Twig_Extension_StringLoader
    tags:      [{name: 'twig.extension'}]


  # Symfony

  app.expression_language:
    class:     Symfony\Component\ExpressionLanguage\ExpressionLanguage
  app.annotation_reader:
    class:     Doctrine\Common\Annotations\AnnotationReader


  # others

  app.redis:
    class: Redis
    calls:
      - ['connect', ['127.0.0.1']]


  # aliases

  redis: '@app.redis'

