services:

  preprocessor.beforestep.conditionals:
    class:     Itq\Common\Plugin\PreprocessorBeforeStep\ConditionalsPreprocessorBeforeStep
    tags:      [{name: 'preprocessor.before_step', id: 'conditionals', priority: 300}]
