services:

  preprocessor.contextdumpers.phpfile:
    class:     Itq\Common\Plugin\ContextDumper\PhpFileContextDumper
    tags:      [{name: 'preprocessor.contextdumper'}]
  preprocessor.contextdumpers.yamlfile:
    class:     Itq\Common\Plugin\ContextDumper\YamlFileContextDumper
    arguments: ['@app.yaml']
    tags:      [{name: 'preprocessor.contextdumper'}]
