services:

  preprocessor.step.errormappings:
    class:     Itq\Common\Plugin\PreprocessorStep\ErrorMappingsPreprocessorStep
    tags:      [{name: 'preprocessor.step', id: 'errormappings', priority: 300}, {name: 'preprocessor.aware.errormappings'}]
    public:    false
  preprocessor.step.annotations:
    class:     Itq\Common\Plugin\PreprocessorStep\AnnotationsPreprocessorStep
    arguments: ['@preprocessor.annotationreader']
    tags:      [{name: 'preprocessor.step', id: 'annotations', priority: 290}, {name: 'preprocessor.aware.annotations'}]
    public:    false
  preprocessor.step.storages:
    class:     Itq\Common\Plugin\PreprocessorStep\StoragesPreprocessorStep
    tags:      [{name: 'preprocessor.step', id: 'storages', priority: 280}, {name: 'preprocessor.aware.storages'}]
    public:    false
  preprocessor.step.dataproviders:
    class:     Itq\Common\Plugin\PreprocessorStep\DataProvidersPreprocessorStep
    tags:      [{name: 'preprocessor.step', id: 'dataproviders', priority: 270}]
    public:    false
  preprocessor.step.tags:
    class:     Itq\Common\Plugin\PreprocessorStep\TagsPreprocessorStep
    tags:      [{name: 'preprocessor.step', id: 'tags', priority: 260}, {name: 'preprocessor.aware.tags'}]
    public:    false
  preprocessor.step.events:
    class:     Itq\Common\Plugin\PreprocessorStep\EventsPreprocessorStep
    tags:      [{name: 'preprocessor.step', id: 'events', priority: 250}, {name: 'preprocessor.aware.events'}]
    public:    false
  preprocessor.step.connections:
    class:     Itq\Common\Plugin\PreprocessorStep\ConnectionsPreprocessorStep
    tags:      [{name: 'preprocessor.step', id: 'connections', priority: 240}, {name: 'preprocessor.aware.connections'}]
    public:    false
  preprocessor.step.registeredcontainermethodcalls:
    class:     Itq\Common\Plugin\PreprocessorStep\RegisteredContainerMethodCallsPreprocessorStep
    tags:      [{name: 'preprocessor.step', id: 'registeredcontainermethodcalls', priority: 230}, {name: 'preprocessor.aware.registeredcontainermethodcalls'}]
    public:    false
  preprocessor.step.contextdumpers:
    class:     Itq\Common\Plugin\PreprocessorStep\ContextDumpersPreprocessorStep
    tags:      [{name: 'preprocessor.step', id: 'contextdumpers', priority: 220}, {name: 'preprocessor.aware.contextdumpers'}]
    public:    false
